services:
  firestore-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:577.0.0-emulators
    container_name: dual-weather-firestore
    ports:
      - "8002:8080"
    command: >
      gcloud emulators firestore start
      --host-port=0.0.0.0:8080
